# Generated by Django 5.2.8 on 2025-11-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('ceremony', 'Wedding Ceremony'), ('reception', 'Reception'), ('photoshoot', 'Photo Shoot'), ('dinner', 'Dinner'), ('party', 'After Party'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='fa fa-heart', help_text='FontAwesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order'],
            },
        ),
    ]
