# Generated by Django 5.2.8 on 2025-11-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('bridesmaid', 'Bridesmaid'), ('groomsman', 'Groomsman'), ('maid_of_honor', 'Maid of Honor'), ('best_man', 'Best Man'), ('flower_girl', 'Flower Girl'), ('ring_bearer', 'Ring Bearer'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='static/img/team-1.jpg', upload_to='team/')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['role', 'order'],
            },
        ),
    ]
