# Generated by Django 5.2.8 on 2025-11-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('response', models.CharField(choices=[('yes', 'Yes, I will attend'), ('no', 'No, I cannot attend'), ('maybe', 'Maybe')], max_length=10)),
                ('number_of_guests', models.IntegerField(default=1)),
                ('meal_preference', models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten Free')], max_length=20)),
                ('dietary_requirements', models.TextField(blank=True)),
                ('special_requests', models.TextField(blank=True)),
                ('message', models.TextField(blank=True, help_text='Special message for the couple')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSVP Response',
                'verbose_name_plural': 'RSVP Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('map_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('dress_code', models.CharField(blank=True, max_length=100)),
                ('is_main_event', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wedding Event',
                'verbose_name_plural': 'Wedding Events',
                'ordering': ['date'],
            },
        ),
    ]
